version: '3.3'
services:

  cassandra-oai:
    hostname: cassandra-oai
    image: cassandra:3.11
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    user: "999:999"
    volumes:
    - ${OAI_DATA_FOLDER}/data/cassandra:/var/lib/cassandra/
    - ${OAI_DATA_FOLDER}/configs/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
    - ${OAI_DATA_FOLDER}/configs/cassandra/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
    - ${OAI_DATA_FOLDER}/configs/cassandra/init-fizoai-database.sh:/etc/cassandra/init-fizoai-database.sh
    ports:
    - '9042:9042'


  elasticsearch-oai:
    hostname: elasticsearch-oai
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms2g -Xmx2g"
      - "LOG4J_FORMAT_MSG_NO_LOOKUPS=true"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    user: "1000:1000"
    volumes:
    - ${OAI_DATA_FOLDER}/logs/elasticsearch_oai:/usr/share/elasticsearch/logs
    - ${OAI_DATA_FOLDER}/data/elasticsearch_oai/es-data:/usr/share/elasticsearch/es-data
    - ${OAI_DATA_FOLDER}/configs/elasticsearch_oai/oai-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
    - '9200:9200'

  elasticsearch-oai-setup:
    hostname: elasticsearch-oai-setup
    image: curlimages/curl:7.85.0
    depends_on:
    - elasticsearch-oai
    command: sh /usr/share/elasticsearch/config/init-fizoai-elasticsearch.sh
    volumes:
    - ${OAI_DATA_FOLDER}/configs/elasticsearch_oai/init-fizoai-elasticsearch.sh:/usr/share/elasticsearch/config/init-fizoai-elasticsearch.sh:ro



  oai-backend:
    hostname: oai-backend
    image: docker.dev.fiz-karlsruhe.de/oai-backend:1.3-SNAPSHOT
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    depends_on:
    - cassandra-oai
    - elasticsearch-oai
    links: 
    - "cassandra-oai"
    - "elasticsearch-oai"
    volumes:
    - ${OAI_DATA_FOLDER}/configs/oai_backend/fiz-oai-backend.properties:/usr/local/tomcat/conf/fiz-oai-backend.properties:ro
    - ${OAI_DATA_FOLDER}/logs/oai_backend/:/usr/local/tomcat/logs
    ports:
    - '8081:8080'
    

  oai-provider:
    hostname: oai-provider
    image: docker.dev.fiz-karlsruhe.de/oai-provider:1.3-SNAPSHOT
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    depends_on:
    - oai-backend
    links: 
    - "oai-backend"
    volumes:
    - ${OAI_DATA_FOLDER}/configs/oai_provider/oaicat.properties:/usr/local/tomcat/conf/oaicat.properties:ro
    - ${OAI_DATA_FOLDER}/logs/oai_provider/:/usr/local/tomcat/logs
    ports:
    - '8080:8080'
