version: '3.3'
services:

  cassandra-oai:
    hostname: cassandra-oai
    image: cassandra:3.11
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    user: "999:999"
    volumes:
    - ${OAI_DATA_FOLDER}/data/cassandra:/var/lib/cassandra/
    - ${OAI_DATA_FOLDER}/configs/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
    - ${OAI_DATA_FOLDER}/configs/cassandra/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
    - ${OAI_DATA_FOLDER}/configs/cassandra_escidocng/jmxremote.access:/opt/java/openjdk/lib/management/jmxremote.access
    - ${OAI_DATA_FOLDER}/configs/cassandra_escidocng/jmxremote.password:/etc/cassandra/jmxremote.password
    ports:
    - '9042:9042'


  cassandra-oai-setup:
    hostname: cassandra-oai-setup
    image: cassandra:3.11
    depends_on:
    - cassandra-oai
    command: ["/wait-for-it.sh","cassandra-oai:9042","--", "sh", "/init-fizoai-database.sh"]
    volumes:
    - ${OAI_DATA_FOLDER}/configs/cassandra/init-fizoai-database.sh:/init-fizoai-database.sh:ro
    - ${OAI_DATA_FOLDER}/configs/cassandra/wait-for-it.sh:/wait-for-it.sh:ro

  cassandra-backup:
    hostname: cassandra-backup
    image: docker.dev.fiz-karlsruhe.de/cassandra-backup:1
    environment:
      JAVA_OPTS: "-Dlog4j2.formatMsgNoLookups=true"
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    env_file:
    - .cassandra_dump_env
    volumes:
    - ${OAI_DATA_FOLDER}/logs/cassandra-backup:/logs
    - ${OAI_DATA_FOLDER}/data/cassandra:/source_data
    - ${OAI_DATA_FOLDER}/data/cassandra-backup:/backup
    depends_on:
    - cassandra-oai


  elasticsearch-oai:
    hostname: elasticsearch-oai
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms2g -Xmx2g"
      - "LOG4J_FORMAT_MSG_NO_LOOKUPS=true"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    user: "1000:1000"
    volumes:
    - ${OAI_DATA_FOLDER}/logs/elasticsearch_oai:/usr/share/elasticsearch/logs
    - ${OAI_DATA_FOLDER}/data/elasticsearch_oai/es-data:/usr/share/elasticsearch/es-data
    - ${OAI_DATA_FOLDER}/configs/elasticsearch_oai/oai-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
    - '9200:9200'

  elasticsearch-oai-setup:
    hostname: elasticsearch-oai-setup
    image: curlimages/curl:7.85.0
    depends_on:
    - elasticsearch-oai
    #command: ["/wait-for-it.sh","elasticsearch-oai:9200","--", "/init-fizoai-elasticsearch.sh"]
    command: "/init-fizoai-elasticsearch.sh"
    volumes:
    - ${OAI_DATA_FOLDER}/configs/elasticsearch_oai/init-fizoai-elasticsearch.sh:/init-fizoai-elasticsearch.sh:ro
    - ${OAI_DATA_FOLDER}/configs/elasticsearch_oai/item_mapping_es_v7:/item_mapping_es_v7:ro


  oai-backend:
    hostname: oai-backend
    image: docker.dev.fiz-karlsruhe.de/oai-backend:1.2.4
    environment:
    - "LOG4J_FORMAT_MSG_NO_LOOKUPS=true"
    - "CATALINA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true"
    depends_on:
    - cassandra-oai
    - elasticsearch-oai
    links: 
    - "cassandra-oai"
    - "elasticsearch-oai"
    volumes:
    - ${OAI_DATA_FOLDER}/configs/oai_backend/fiz-oai-backend.properties:/usr/local/tomcat/conf/fiz-oai-backend.properties:ro
    - ${OAI_DATA_FOLDER}/logs/oai_backend/:/usr/local/tomcat/logs
    ports:
    - '8081:8080'
    

  oai-provider:
    hostname: oai-provider
    image: docker.dev.fiz-karlsruhe.de/oai-provider:1.2.2
    environment:
    - "LOG4J_FORMAT_MSG_NO_LOOKUPS=true"
    - "CATALINA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true"
    depends_on:
    - oai-backend
    links: 
    - "oai-backend"
    volumes:
    - ${OAI_DATA_FOLDER}/configs/oai_provider/oaicat.properties:/usr/local/tomcat/conf/oaicat.properties:ro
    - ${OAI_DATA_FOLDER}/logs/oai_provider/:/usr/local/tomcat/logs
    ports:
    - '8080:8080'
