apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap-cassandra.yaml
  - configmap-cassandra-scripts.yaml
  - configmap-elasticsearch.yaml
  - configmap-oai-backend.yaml
  - configmap-oai-provider.yaml
  - cassandra-statefulset.yaml
  - cassandra-init-job.yaml
  - elasticsearch-statefulset.yaml
  - elasticsearch-init-job.yaml
  - oai-backend.yaml
  - oai-provider.yaml
  - ingress.yaml
